package simulation.math.hexagon;

public enum HexagonCorner
{
	HEXAGON_CORNER_UP,
	HEXAGON_CORNER_UP_RIGHT,
	HEXAGON_CORNER_DOWN_RIGHT,
	HEXAGON_CORNER_DOWN,
	HEXAGON_CORNER_DOWN_LEFT,
	HEXAGON_CORNER_UP_LEFT;
}
